# Events: def. true
# Colors: def. gray [black, dark_blue, dark_green, dark_aqua, dark_red, dark_purple, gold, gray, dark_gray, blue, green, aqua, red, light_purple, yellow, white]
# IdleTimer: def. true, 60 sec
# Messages: def. true (keys: {DISPLAYNAME}, {TIME})
Events:
  move: true
  chat: true
Colors:
  message: 'gray'
  player: 'gray'
IdleTimer:
  enabled: true
  period: 60
Messages:
  enabled: true
  +afk: '{DISPLAYNAME} is now AFK'
  -afk: '{DISPLAYNAME} is no longer AFK'
