# Events: def. true
# Colors: def. gray [black, dark_blue, dark_green, dark_aqua, dark_red, purple, gold, gray, dark_gray, indigo, bright_green, aqua, red, pink, yellow, white]
# IdleTimer: def. true, 60 sec
# Messages: def. true (keys: {PLAYER}, {TIME})
Events:
  move: true
  chat: true
Colors:
  message: 'gray'
  player: 'gray'
IdleTimer:
  enabled: true
  period: 60
Messages:
  enabled: true
  +afk: '{PLAYER} is now AFK'
  -afk: '{PLAYER} is no longer AFK'
