name: AFK
main: com.github.alesvojta.afk.AFK
version: 4.0.0
author: schneckk
description: Provides AFK messages
website: http://dev.bukkit.org/server-mods/afk/

commands:
  afk:
    description: Provides AFK message when player types /afk.
    usage: /<command>
